# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # DiagnosticsSubscriptionsController
  class DiagnosticsSubscriptionsController < BaseController
    # This endpoint retrieves a diagnostics subscription by account.
    # @param [String] account_name Required parameter: Account identifier.
    # @return [DiagnosticsSubscription] response from the API call
    def get_diagnostics_subscription(account_name)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/subscriptions',
                                     Server::DEVICE_DIAGNOSTICS)
                   .query_param(new_parameter(account_name, key: 'accountName'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('oAuth2')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(DiagnosticsSubscription.method(:from_hash))
                   .is_api_response(true)
                   .local_error('default',
                                'Error response.',
                                DeviceDiagnosticsResultException))
        .execute
    end
  end
end
