# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Utility class for custom header authorization.
  class VzM2mToken < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'VZM2MToken: vz_m2m_token is undefined.'
    end

    # Initialization constructor.
    def initialize(vz_m2m_token_credentials)
      auth_params = {}
      auth_params['VZ-M2M-Token'] = vz_m2m_token_credentials.vz_m2m_token unless
        vz_m2m_token_credentials.nil? || vz_m2m_token_credentials.vz_m2m_token.nil?

      super auth_params
    end
  end

  # Data class for VZM2MTokenCredentials.
  # Data class for VZM2MTokenCredentials.
  class VZM2MTokenCredentials
    attr_reader :vz_m2m_token

    def initialize(vz_m2m_token:)
      raise ArgumentError, 'vz_m2m_token cannot be nil' if vz_m2m_token.nil?

      @vz_m2m_token = vz_m2m_token
    end

    def clone_with(vz_m2m_token: nil)
      vz_m2m_token ||= self.vz_m2m_token

      VZM2MTokenCredentials.new(vz_m2m_token: vz_m2m_token)
    end
  end
end
