# verizon_thing_space_quality_of_service_api_endpoints
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module VerizonThingSpaceQualityOfServiceApiEndpoints
  # Utility class for custom header authorization.
  class VzM2mSessionToken < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'VzM2mSessionToken: vz_m2_m_token is undefined.'
    end

    # Initialization constructor.
    def initialize(vz_m2m_session_token_credentials)
      auth_params = {}
      auth_params['VZ-M2M-Token'] = vz_m2m_session_token_credentials.vz_m2_m_token unless
        vz_m2m_session_token_credentials.nil? || vz_m2m_session_token_credentials.vz_m2_m_token.nil?

      super auth_params
    end
  end

  # Data class for VzM2mSessionTokenCredentials.
  # Data class for VzM2mSessionTokenCredentials.
  class VzM2mSessionTokenCredentials
    attr_reader :vz_m2_m_token

    def initialize(vz_m2_m_token:)
      raise ArgumentError, 'vz_m2_m_token cannot be nil' if vz_m2_m_token.nil?

      @vz_m2_m_token = vz_m2_m_token
    end

    def clone_with(vz_m2_m_token: nil)
      vz_m2_m_token ||= self.vz_m2_m_token

      VzM2mSessionTokenCredentials.new(vz_m2_m_token: vz_m2_m_token)
    end
  end
end
