# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # AccessIntents Model.
  class AccessIntents < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :enable_carrier_network_access

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enable_carrier_network_access'] = 'enableCarrierNetworkAccess'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        enable_carrier_network_access
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(enable_carrier_network_access = false)
      unless enable_carrier_network_access == SKIP
        @enable_carrier_network_access =
          enable_carrier_network_access
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enable_carrier_network_access =
        hash['enableCarrierNetworkAccess'] ||= false

      # Create object from extracted values.
      AccessIntents.new(enable_carrier_network_access)
    end
  end
end
