# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module Verizon
  # The list of devices that have licenses assigned, including the date and time
  # of when each license was assigned.
  class AccountLicenseDeviceListItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Device IMEI.
    # @return [String]
    attr_accessor :device_id

    # Timestamp of when a license was assigned to the device.
    # @return [DateTime]
    attr_accessor :assignment_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_id'] = 'deviceId'
      @_hash['assignment_time'] = 'assignmentTime'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        device_id
        assignment_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_id = SKIP,
                   assignment_time = SKIP)
      @device_id = device_id unless device_id == SKIP
      @assignment_time = assignment_time unless assignment_time == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      device_id = hash.key?('deviceId') ? hash['deviceId'] : SKIP
      assignment_time = if hash.key?('assignmentTime')
                          (DateTimeHelper.from_rfc3339(hash['assignmentTime']) if hash['assignmentTime'])
                        else
                          SKIP
                        end

      # Create object from extracted values.
      AccountLicenseDeviceListItem.new(device_id,
                                       assignment_time)
    end

    def to_custom_assignment_time
      DateTimeHelper.to_rfc3339(assignment_time)
    end
  end
end
