# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Addressquery Model.
  class Addressquery < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Address]]
    attr_accessor :address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address'] = 'address'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(address = SKIP)
      @address = address unless address == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      address = nil
      unless hash['address'].nil?
        address = []
        hash['address'].each do |structure|
          address << (Address.from_hash(structure) if structure)
        end
      end

      address = SKIP unless hash.key?('address')

      # Create object from extracted values.
      Addressquery.new(address)
    end
  end
end
