# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Contains usage information per device.
  class AggregateUsageItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # International Mobile Equipment Identifier. This is the ID of the device
    # reporting usage.
    # @return [String]
    attr_accessor :imei

    # Number of sessions established by the device reporting usage.
    # @return [Integer]
    attr_accessor :number_of_sessions

    # The amount of data transferred by the device reporting usage, measured in
    # Bytes.
    # @return [Integer]
    attr_accessor :bytes_transferred

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['imei'] = 'imei'
      @_hash['number_of_sessions'] = 'numberOfSessions'
      @_hash['bytes_transferred'] = 'bytesTransferred'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        imei
        number_of_sessions
        bytes_transferred
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(imei = SKIP,
                   number_of_sessions = SKIP,
                   bytes_transferred = SKIP)
      @imei = imei unless imei == SKIP
      @number_of_sessions = number_of_sessions unless number_of_sessions == SKIP
      @bytes_transferred = bytes_transferred unless bytes_transferred == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      imei = hash.key?('imei') ? hash['imei'] : SKIP
      number_of_sessions =
        hash.key?('numberOfSessions') ? hash['numberOfSessions'] : SKIP
      bytes_transferred =
        hash.key?('bytesTransferred') ? hash['bytesTransferred'] : SKIP

      # Create object from extracted values.
      AggregateUsageItem.new(imei,
                             number_of_sessions,
                             bytes_transferred)
    end
  end
end
