# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Error reported by a device.
  class AggregateUsageError < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # International Mobile Equipment Identifier. This is the ID of the device
    # reporting errors.
    # @return [String]
    attr_accessor :imei

    # A general error message.
    # @return [String]
    attr_accessor :error_message

    # Error message.
    # @return [IErrorMessage]
    attr_accessor :error_response

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['imei'] = 'imei'
      @_hash['error_message'] = 'errorMessage'
      @_hash['error_response'] = 'errorResponse'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        imei
        error_message
        error_response
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(imei = SKIP,
                   error_message = SKIP,
                   error_response = SKIP)
      @imei = imei unless imei == SKIP
      @error_message = error_message unless error_message == SKIP
      @error_response = error_response unless error_response == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      imei = hash.key?('imei') ? hash['imei'] : SKIP
      error_message = hash.key?('errorMessage') ? hash['errorMessage'] : SKIP
      error_response = IErrorMessage.from_hash(hash['errorResponse']) if hash['errorResponse']

      # Create object from extracted values.
      AggregateUsageError.new(imei,
                              error_message,
                              error_response)
    end
  end
end
