# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Information required to associate a usage segmentation label with a device
  # to retrieve billing.
  class BilledusageListRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [LabelsList]
    attr_accessor :labels

    # TODO: Write general description for this method
    # @return [Array[DeviceList]]
    attr_accessor :devices

    # TODO: Write general description for this method
    # @return [BillingCycle]
    attr_accessor :billing_cycle

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['labels'] = 'labels'
      @_hash['devices'] = 'devices'
      @_hash['billing_cycle'] = 'BillingCycle'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_name
        labels
        devices
        billing_cycle
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = SKIP,
                   labels = SKIP,
                   devices = SKIP,
                   billing_cycle = SKIP)
      @account_name = account_name unless account_name == SKIP
      @labels = labels unless labels == SKIP
      @devices = devices unless devices == SKIP
      @billing_cycle = billing_cycle unless billing_cycle == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP
      labels = LabelsList.from_hash(hash['labels']) if hash['labels']
      # Parameter is an array, so we need to iterate through it
      devices = nil
      unless hash['devices'].nil?
        devices = []
        hash['devices'].each do |structure|
          devices << (DeviceList.from_hash(structure) if structure)
        end
      end

      devices = SKIP unless hash.key?('devices')
      billing_cycle = BillingCycle.from_hash(hash['BillingCycle']) if hash['BillingCycle']

      # Create object from extracted values.
      BilledusageListRequest.new(account_name,
                                 labels,
                                 devices,
                                 billing_cycle)
    end
  end
end
