# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # BillingCycle Model.
  class BillingCycle < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :year

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :month

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['year'] = 'year'
      @_hash['month'] = 'month'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        year
        month
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(year = SKIP,
                   month = SKIP)
      @year = year unless year == SKIP
      @month = month unless month == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      year = hash.key?('year') ? hash['year'] : SKIP
      month = hash.key?('month') ? hash['month'] : SKIP

      # Create object from extracted values.
      BillingCycle.new(year,
                       month)
    end
  end
end
