# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Bill usage request.
  class BillUsageRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account identifier.
    # @return [String]
    attr_accessor :account_name

    # Start date to search for billable usage, mm-dd-yyyy.
    # @return [String]
    attr_accessor :start_date

    # End date to search for billable usage, mm-dd-yyyy.
    # @return [String]
    attr_accessor :end_date

    # Request usage for single or multiple accounts.
    # @return [TrueClass | FalseClass]
    attr_accessor :usage_for_all_accounts

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['start_date'] = 'startDate'
      @_hash['end_date'] = 'endDate'
      @_hash['usage_for_all_accounts'] = 'usageForAllAccounts'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        usage_for_all_accounts
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = nil,
                   start_date = nil,
                   end_date = nil,
                   usage_for_all_accounts = SKIP)
      @account_name = account_name
      @start_date = start_date
      @end_date = end_date
      @usage_for_all_accounts = usage_for_all_accounts unless usage_for_all_accounts == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : nil
      start_date = hash.key?('startDate') ? hash['startDate'] : nil
      end_date = hash.key?('endDate') ? hash['endDate'] : nil
      usage_for_all_accounts =
        hash.key?('usageForAllAccounts') ? hash['usageForAllAccounts'] : SKIP

      # Create object from extracted values.
      BillUsageRequest.new(account_name,
                           start_date,
                           end_date,
                           usage_for_all_accounts)
    end
  end
end
