# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Software upgrade information.
  class CampaignSoftwareUpgrade < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Campaign name.
    # @return [String]
    attr_accessor :campaign_name

    # Software name to upgrade to.
    # @return [String]
    attr_accessor :software_name

    # Old software name.
    # @return [String]
    attr_accessor :software_from

    # New software name.
    # @return [String]
    attr_accessor :software_to

    # OMA or HTTP.
    # @return [String]
    attr_accessor :distribution_type

    # Campaign start date.
    # @return [Date]
    attr_accessor :start_date

    # Campaign end date.
    # @return [Date]
    attr_accessor :end_date

    # Specifies starting date client should download package. If null, client
    # will download as soon as possible.
    # @return [Date]
    attr_accessor :download_after_date

    # List of allowed download time windows.
    # @return [Array[V2TimeWindow]]
    attr_accessor :download_time_window_list

    # Client will install package after date. If null, client will install as
    # soon as possible.
    # @return [Date]
    attr_accessor :install_after_date

    # List of allowed install time windows.
    # @return [Array[V2TimeWindow]]
    attr_accessor :install_time_window_list

    # Device IMEI list.
    # @return [Array[String]]
    attr_accessor :device_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['campaign_name'] = 'campaignName'
      @_hash['software_name'] = 'softwareName'
      @_hash['software_from'] = 'softwareFrom'
      @_hash['software_to'] = 'softwareTo'
      @_hash['distribution_type'] = 'distributionType'
      @_hash['start_date'] = 'startDate'
      @_hash['end_date'] = 'endDate'
      @_hash['download_after_date'] = 'downloadAfterDate'
      @_hash['download_time_window_list'] = 'downloadTimeWindowList'
      @_hash['install_after_date'] = 'installAfterDate'
      @_hash['install_time_window_list'] = 'installTimeWindowList'
      @_hash['device_list'] = 'deviceList'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        campaign_name
        download_after_date
        download_time_window_list
        install_after_date
        install_time_window_list
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(software_name = nil,
                   software_from = nil,
                   software_to = nil,
                   distribution_type = nil,
                   start_date = nil,
                   end_date = nil,
                   device_list = nil,
                   campaign_name = SKIP,
                   download_after_date = SKIP,
                   download_time_window_list = SKIP,
                   install_after_date = SKIP,
                   install_time_window_list = SKIP)
      @campaign_name = campaign_name unless campaign_name == SKIP
      @software_name = software_name
      @software_from = software_from
      @software_to = software_to
      @distribution_type = distribution_type
      @start_date = start_date
      @end_date = end_date
      @download_after_date = download_after_date unless download_after_date == SKIP
      unless download_time_window_list == SKIP
        @download_time_window_list =
          download_time_window_list
      end
      @install_after_date = install_after_date unless install_after_date == SKIP
      @install_time_window_list = install_time_window_list unless install_time_window_list == SKIP
      @device_list = device_list
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      software_name = hash.key?('softwareName') ? hash['softwareName'] : nil
      software_from = hash.key?('softwareFrom') ? hash['softwareFrom'] : nil
      software_to = hash.key?('softwareTo') ? hash['softwareTo'] : nil
      distribution_type =
        hash.key?('distributionType') ? hash['distributionType'] : nil
      start_date = hash.key?('startDate') ? hash['startDate'] : nil
      end_date = hash.key?('endDate') ? hash['endDate'] : nil
      device_list = hash.key?('deviceList') ? hash['deviceList'] : nil
      campaign_name = hash.key?('campaignName') ? hash['campaignName'] : SKIP
      download_after_date =
        hash.key?('downloadAfterDate') ? hash['downloadAfterDate'] : SKIP
      # Parameter is an array, so we need to iterate through it
      download_time_window_list = nil
      unless hash['downloadTimeWindowList'].nil?
        download_time_window_list = []
        hash['downloadTimeWindowList'].each do |structure|
          download_time_window_list << (V2TimeWindow.from_hash(structure) if structure)
        end
      end

      download_time_window_list = SKIP unless hash.key?('downloadTimeWindowList')
      install_after_date =
        hash.key?('installAfterDate') ? hash['installAfterDate'] : SKIP
      # Parameter is an array, so we need to iterate through it
      install_time_window_list = nil
      unless hash['installTimeWindowList'].nil?
        install_time_window_list = []
        hash['installTimeWindowList'].each do |structure|
          install_time_window_list << (V2TimeWindow.from_hash(structure) if structure)
        end
      end

      install_time_window_list = SKIP unless hash.key?('installTimeWindowList')

      # Create object from extracted values.
      CampaignSoftwareUpgrade.new(software_name,
                                  software_from,
                                  software_to,
                                  distribution_type,
                                  start_date,
                                  end_date,
                                  device_list,
                                  campaign_name,
                                  download_after_date,
                                  download_time_window_list,
                                  install_after_date,
                                  install_time_window_list)
    end
  end
end
