# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # The request body identifies the devices to upload.
  class CheckOrderStatusRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of a billing account. An account name is usually numeric, and
    # must include any leading zeros.
    # @return [String]
    attr_accessor :account_name

    # The request id from the activation order.
    # @return [String]
    attr_accessor :order_request_id

    # The devices to upload, specified by device IDs in a format matching
    # uploadType.
    # @return [Array[DeviceList]]
    attr_accessor :devices

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['order_request_id'] = 'orderRequestId'
      @_hash['devices'] = 'devices'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        order_request_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = nil,
                   devices = nil,
                   order_request_id = SKIP)
      @account_name = account_name
      @order_request_id = order_request_id unless order_request_id == SKIP
      @devices = devices
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : nil
      # Parameter is an array, so we need to iterate through it
      devices = nil
      unless hash['devices'].nil?
        devices = []
        hash['devices'].each do |structure|
          devices << (DeviceList.from_hash(structure) if structure)
        end
      end

      devices = nil unless hash.key?('devices')
      order_request_id =
        hash.key?('orderRequestId') ? hash['orderRequestId'] : SKIP

      # Create object from extracted values.
      CheckOrderStatusRequest.new(account_name,
                                  devices,
                                  order_request_id)
    end
  end
end
