# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Cloud provider where you plan to provision and operate your Kubernetes
  # cluster.
  class CloudProviderEnum
    CLOUD_PROVIDER_ENUM = [
      # TODO: Write general description for AWS
      AWS = 'AWS'.freeze,

      # TODO: Write general description for AZURE
      AZURE = 'AZURE'.freeze,

      # TODO: Write general description for GCP
      GCP = 'GCP'.freeze
    ].freeze
  end
end
