# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ClusterType.
  class ClusterTypeEnum
    CLUSTER_TYPE_ENUM = [
      # TODO: Write general description for PUBLICCLOUD
      PUBLICCLOUD = 'publicCloud'.freeze,

      # TODO: Write general description for DATACENTER
      DATACENTER = 'dataCenter'.freeze
    ].freeze
  end
end
