# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ClusterInfraProvision Model.
  class ClusterInfraProvision < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cluster_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :provision_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :created_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :modified_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :organization_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :partner_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :running_state

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :running_status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total_steps

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cluster_id'] = 'cluster_id'
      @_hash['provision_id'] = 'provision_id'
      @_hash['created_at'] = 'created_at'
      @_hash['modified_at'] = 'modified_at'
      @_hash['organization_id'] = 'organization_id'
      @_hash['partner_id'] = 'partner_id'
      @_hash['type'] = 'type'
      @_hash['running_state'] = 'running_state'
      @_hash['running_status'] = 'running_status'
      @_hash['id'] = 'id'
      @_hash['status'] = 'status'
      @_hash['total_steps'] = 'total_steps'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        cluster_id
        provision_id
        created_at
        modified_at
        organization_id
        partner_id
        type
        running_state
        running_status
        id
        status
        total_steps
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(cluster_id = SKIP,
                   provision_id = SKIP,
                   created_at = SKIP,
                   modified_at = SKIP,
                   organization_id = SKIP,
                   partner_id = SKIP,
                   type = SKIP,
                   running_state = SKIP,
                   running_status = SKIP,
                   id = SKIP,
                   status = SKIP,
                   total_steps = SKIP)
      @cluster_id = cluster_id unless cluster_id == SKIP
      @provision_id = provision_id unless provision_id == SKIP
      @created_at = created_at unless created_at == SKIP
      @modified_at = modified_at unless modified_at == SKIP
      @organization_id = organization_id unless organization_id == SKIP
      @partner_id = partner_id unless partner_id == SKIP
      @type = type unless type == SKIP
      @running_state = running_state unless running_state == SKIP
      @running_status = running_status unless running_status == SKIP
      @id = id unless id == SKIP
      @status = status unless status == SKIP
      @total_steps = total_steps unless total_steps == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cluster_id = hash.key?('cluster_id') ? hash['cluster_id'] : SKIP
      provision_id = hash.key?('provision_id') ? hash['provision_id'] : SKIP
      created_at = hash.key?('created_at') ? hash['created_at'] : SKIP
      modified_at = hash.key?('modified_at') ? hash['modified_at'] : SKIP
      organization_id =
        hash.key?('organization_id') ? hash['organization_id'] : SKIP
      partner_id = hash.key?('partner_id') ? hash['partner_id'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      running_state = hash.key?('running_state') ? hash['running_state'] : SKIP
      running_status =
        hash.key?('running_status') ? hash['running_status'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      total_steps = hash.key?('total_steps') ? hash['total_steps'] : SKIP

      # Create object from extracted values.
      ClusterInfraProvision.new(cluster_id,
                                provision_id,
                                created_at,
                                modified_at,
                                organization_id,
                                partner_id,
                                type,
                                running_state,
                                running_status,
                                id,
                                status,
                                total_steps)
    end
  end
end
