# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # CreateTargetRequestFields Model.
  class CreateTargetRequestFields < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [FieldsHttpHeaders]
    attr_accessor :httpheaders

    # List of device types.
    # @return [Array[String]]
    attr_accessor :devicetypes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['httpheaders'] = 'httpheaders'
      @_hash['devicetypes'] = 'devicetypes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        httpheaders
        devicetypes
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(httpheaders = SKIP,
                   devicetypes = SKIP)
      @httpheaders = httpheaders unless httpheaders == SKIP
      @devicetypes = devicetypes unless devicetypes == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      httpheaders = FieldsHttpHeaders.from_hash(hash['httpheaders']) if hash['httpheaders']
      devicetypes = hash.key?('devicetypes') ? hash['devicetypes'] : SKIP

      # Create object from extracted values.
      CreateTargetRequestFields.new(httpheaders,
                                    devicetypes)
    end
  end
end
