# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Request to delete a device request.
  class DeleteDevicesRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A list of up to 100 devices that you want to delete, specified by device
    # identifier. You only need to provide one identifier per device.
    # @return [Array[AccountDeviceList]]
    attr_accessor :devices_to_delete

    # The Verizon billing account that the device group belongs to. An account
    # name is usually numeric, and must include any leading zeros.
    # @return [String]
    attr_accessor :account_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['devices_to_delete'] = 'devicesToDelete'
      @_hash['account_name'] = 'accountName'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(devices_to_delete = nil,
                   account_name = SKIP)
      @devices_to_delete = devices_to_delete
      @account_name = account_name unless account_name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      devices_to_delete = nil
      unless hash['devicesToDelete'].nil?
        devices_to_delete = []
        hash['devicesToDelete'].each do |structure|
          devices_to_delete << (AccountDeviceList.from_hash(structure) if structure)
        end
      end

      devices_to_delete = nil unless hash.key?('devicesToDelete')
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP

      # Create object from extracted values.
      DeleteDevicesRequest.new(devices_to_delete,
                               account_name)
    end
  end
end
