# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # DeploymentLocation Model.
  class DeploymentLocation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Edge Resource Number.
    # @return [String]
    attr_accessor :ern

    # Edge Resource Number.
    # @return [DeploymentLocationCluster]
    attr_accessor :cluster

    # Edge Resource Number.
    # @return [DeploymentLocationNamespace]
    attr_accessor :namespace

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ern'] = 'ern'
      @_hash['cluster'] = 'cluster'
      @_hash['namespace'] = 'namespace'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ern
        cluster
        namespace
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(ern = SKIP,
                   cluster = SKIP,
                   namespace = SKIP)
      @ern = ern unless ern == SKIP
      @cluster = cluster unless cluster == SKIP
      @namespace = namespace unless namespace == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ern = hash.key?('ern') ? hash['ern'] : SKIP
      cluster = DeploymentLocationCluster.from_hash(hash['cluster']) if hash['cluster']
      namespace = DeploymentLocationNamespace.from_hash(hash['namespace']) if hash['namespace']

      # Create object from extracted values.
      DeploymentLocation.new(ern,
                             cluster,
                             namespace)
    end
  end
end
