# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Device service information.
  class DeviceServiceInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # ResponseCode and/or a message indicating success or failure of the
    # request.
    # @return [ApiResponseCode]
    attr_accessor :response_type

    # The International Mobile Equipment Identifier of the device.
    # @return [String]
    attr_accessor :imei

    # Shows if Hyper Precise is enabled (true) or disabled (false).
    # @return [TrueClass | FalseClass]
    attr_accessor :bullseye_enable

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['response_type'] = 'responseType'
      @_hash['imei'] = 'imei'
      @_hash['bullseye_enable'] = 'BullseyeEnable'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        response_type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(imei = nil,
                   bullseye_enable = nil,
                   response_type = SKIP)
      @response_type = response_type unless response_type == SKIP
      @imei = imei
      @bullseye_enable = bullseye_enable
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      imei = hash.key?('imei') ? hash['imei'] : nil
      bullseye_enable =
        hash.key?('BullseyeEnable') ? hash['BullseyeEnable'] : nil
      response_type = ApiResponseCode.from_hash(hash['responseType']) if hash['responseType']

      # Create object from extracted values.
      DeviceServiceInformation.new(imei,
                                   bullseye_enable,
                                   response_type)
    end
  end
end
