# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # The devices that you want to locate. The array cannot contain more than 20
  # devices.
  class DeviceInfo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Device identifier.
    # @return [String]
    attr_accessor :id

    # Device identifier kind.
    # @return [String]
    attr_accessor :kind

    # Device MDN.
    # @return [String]
    attr_accessor :mdn

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['kind'] = 'kind'
      @_hash['mdn'] = 'mdn'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = nil,
                   kind = nil,
                   mdn = nil)
      @id = id
      @kind = kind
      @mdn = mdn
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : nil
      kind = hash.key?('kind') ? hash['kind'] : nil
      mdn = hash.key?('mdn') ? hash['mdn'] : nil

      # Create object from extracted values.
      DeviceInfo.new(id,
                     kind,
                     mdn)
    end
  end
end
