# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Firmware protocol. Valid values include: LWM2M, OMADM, HTTP.
  class DevicesProtocolEnum
    DEVICES_PROTOCOL_ENUM = [
      # TODO: Write general description for LW_M2M
      LW_M2M = 'LWM2M'.freeze,

      # TODO: Write general description for OMDADM
      OMDADM = 'OMDADM'.freeze,

      # TODO: Write general description for HTTP
      HTTP = 'HTTP'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      DEVICES_PROTOCOL_ENUM.include?(value)
    end
  end
end
