# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Device Firmware Information.
  class DeviceFirmwareList < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account name.
    # @return [String]
    attr_accessor :account_name

    # List of device & firmware.
    # @return [Array[DeviceFirmwareVersion]]
    attr_accessor :device_firmwar_version_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['device_firmwar_version_list'] = 'deviceFirmwarVersionList'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        device_firmwar_version_list
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = nil,
                   device_firmwar_version_list = SKIP)
      @account_name = account_name
      unless device_firmwar_version_list == SKIP
        @device_firmwar_version_list =
          device_firmwar_version_list
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : nil
      # Parameter is an array, so we need to iterate through it
      device_firmwar_version_list = nil
      unless hash['deviceFirmwarVersionList'].nil?
        device_firmwar_version_list = []
        hash['deviceFirmwarVersionList'].each do |structure|
          device_firmwar_version_list << (DeviceFirmwareVersion.from_hash(structure) if structure)
        end
      end

      device_firmwar_version_list = SKIP unless hash.key?('deviceFirmwarVersionList')

      # Create object from extracted values.
      DeviceFirmwareList.new(account_name,
                             device_firmwar_version_list)
    end
  end
end
