# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module Verizon
  # EdgeServiceWorkload Model.
  class EdgeServiceWorkload < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # Name of the workload needs to be deployed.
    # @return [String]
    attr_accessor :name

    # Name of the workload needs to be deployed.
    # @return [String]
    attr_accessor :description

    # Deployment package type.
    # @return [PackageTypeEnum]
    attr_accessor :package_type

    # Deployment package type.
    # @return [WorkloadUploadTypeEnum]
    attr_accessor :upload_type

    # Deployment package type.
    # @return [RepositoryTypeEnum]
    attr_accessor :repository_type

    # Deployment package type.
    # @return [String]
    attr_accessor :repository_id

    # Deployment package type.
    # @return [EdgeServiceRepository]
    attr_accessor :repository

    # Deployment package type.
    # @return [Array[String]]
    attr_accessor :files

    # Deployment package type.
    # @return [RevisionTypeEnum]
    attr_accessor :revision_type

    # Deployment package type.
    # @return [ServiceLaunchHelmGitBranch]
    attr_accessor :helm_git_branch

    # Deployment package type.
    # @return [ServiceLaunchHelmGitTag]
    attr_accessor :helm_git_tag

    # Deployment package type.
    # @return [ServiceLaunchHelmYamlGitTag]
    attr_accessor :helm_yaml_git_tag

    # Deployment package type.
    # @return [ServiceLaunchHelmRepo]
    attr_accessor :helm_repo

    # Deployment package type.
    # @return [ServiceLaunchYamlGitBranch]
    attr_accessor :yaml_git_branch

    # Deployment package type.
    # @return [ServiceLaunchTerraformGitBranch]
    attr_accessor :terraform_git_branch

    # Deployment package type.
    # @return [ServiceLaunchTerraformGitTag]
    attr_accessor :terraform_git_tag

    # Deployment package type.
    # @return [DateTime]
    attr_accessor :created_date

    # Deployment package type.
    # @return [DateTime]
    attr_accessor :last_modified_dte

    # Deployment package type.
    # @return [String]
    attr_accessor :created_by

    # Deployment package type.
    # @return [String]
    attr_accessor :updated_by

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['description'] = 'description'
      @_hash['package_type'] = 'packageType'
      @_hash['upload_type'] = 'uploadType'
      @_hash['repository_type'] = 'repositoryType'
      @_hash['repository_id'] = 'repositoryId'
      @_hash['repository'] = 'repository'
      @_hash['files'] = 'files'
      @_hash['revision_type'] = 'revisionType'
      @_hash['helm_git_branch'] = 'helmGitBranch'
      @_hash['helm_git_tag'] = 'helmGitTag'
      @_hash['helm_yaml_git_tag'] = 'helmYamlGitTag'
      @_hash['helm_repo'] = 'helmRepo'
      @_hash['yaml_git_branch'] = 'yamlGitBranch'
      @_hash['terraform_git_branch'] = 'terraformGitBranch'
      @_hash['terraform_git_tag'] = 'terraformGitTag'
      @_hash['created_date'] = 'createdDate'
      @_hash['last_modified_dte'] = 'lastModifiedDte'
      @_hash['created_by'] = 'createdBy'
      @_hash['updated_by'] = 'updatedBy'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        description
        package_type
        upload_type
        repository_type
        repository_id
        repository
        files
        revision_type
        helm_git_branch
        helm_git_tag
        helm_yaml_git_tag
        helm_repo
        yaml_git_branch
        terraform_git_branch
        terraform_git_tag
        created_date
        last_modified_dte
        created_by
        updated_by
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        description
        package_type
        upload_type
        repository_type
        repository_id
        revision_type
      ]
    end

    def initialize(name = nil,
                   id = SKIP,
                   description = SKIP,
                   package_type = SKIP,
                   upload_type = SKIP,
                   repository_type = SKIP,
                   repository_id = SKIP,
                   repository = SKIP,
                   files = SKIP,
                   revision_type = SKIP,
                   helm_git_branch = SKIP,
                   helm_git_tag = SKIP,
                   helm_yaml_git_tag = SKIP,
                   helm_repo = SKIP,
                   yaml_git_branch = SKIP,
                   terraform_git_branch = SKIP,
                   terraform_git_tag = SKIP,
                   created_date = SKIP,
                   last_modified_dte = SKIP,
                   created_by = SKIP,
                   updated_by = SKIP)
      @id = id unless id == SKIP
      @name = name
      @description = description unless description == SKIP
      @package_type = package_type unless package_type == SKIP
      @upload_type = upload_type unless upload_type == SKIP
      @repository_type = repository_type unless repository_type == SKIP
      @repository_id = repository_id unless repository_id == SKIP
      @repository = repository unless repository == SKIP
      @files = files unless files == SKIP
      @revision_type = revision_type unless revision_type == SKIP
      @helm_git_branch = helm_git_branch unless helm_git_branch == SKIP
      @helm_git_tag = helm_git_tag unless helm_git_tag == SKIP
      @helm_yaml_git_tag = helm_yaml_git_tag unless helm_yaml_git_tag == SKIP
      @helm_repo = helm_repo unless helm_repo == SKIP
      @yaml_git_branch = yaml_git_branch unless yaml_git_branch == SKIP
      @terraform_git_branch = terraform_git_branch unless terraform_git_branch == SKIP
      @terraform_git_tag = terraform_git_tag unless terraform_git_tag == SKIP
      @created_date = created_date unless created_date == SKIP
      @last_modified_dte = last_modified_dte unless last_modified_dte == SKIP
      @created_by = created_by unless created_by == SKIP
      @updated_by = updated_by unless updated_by == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : nil
      id = hash.key?('id') ? hash['id'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      package_type = hash.key?('packageType') ? hash['packageType'] : SKIP
      upload_type = hash.key?('uploadType') ? hash['uploadType'] : SKIP
      repository_type =
        hash.key?('repositoryType') ? hash['repositoryType'] : SKIP
      repository_id = hash.key?('repositoryId') ? hash['repositoryId'] : SKIP
      repository = EdgeServiceRepository.from_hash(hash['repository']) if hash['repository']
      files = hash.key?('files') ? hash['files'] : SKIP
      revision_type = hash.key?('revisionType') ? hash['revisionType'] : SKIP
      helm_git_branch = ServiceLaunchHelmGitBranch.from_hash(hash['helmGitBranch']) if
        hash['helmGitBranch']
      helm_git_tag = ServiceLaunchHelmGitTag.from_hash(hash['helmGitTag']) if hash['helmGitTag']
      helm_yaml_git_tag = ServiceLaunchHelmYamlGitTag.from_hash(hash['helmYamlGitTag']) if
        hash['helmYamlGitTag']
      helm_repo = ServiceLaunchHelmRepo.from_hash(hash['helmRepo']) if hash['helmRepo']
      yaml_git_branch = ServiceLaunchYamlGitBranch.from_hash(hash['yamlGitBranch']) if
        hash['yamlGitBranch']
      if hash['terraformGitBranch']
        terraform_git_branch = ServiceLaunchTerraformGitBranch.from_hash(hash['terraformGitBranch'])
      end
      terraform_git_tag = ServiceLaunchTerraformGitTag.from_hash(hash['terraformGitTag']) if
        hash['terraformGitTag']
      created_date = if hash.key?('createdDate')
                       (DateTimeHelper.from_rfc3339(hash['createdDate']) if hash['createdDate'])
                     else
                       SKIP
                     end
      last_modified_dte = if hash.key?('lastModifiedDte')
                            (DateTimeHelper.from_rfc3339(hash['lastModifiedDte']) if hash['lastModifiedDte'])
                          else
                            SKIP
                          end
      created_by = hash.key?('createdBy') ? hash['createdBy'] : SKIP
      updated_by = hash.key?('updatedBy') ? hash['updatedBy'] : SKIP

      # Create object from extracted values.
      EdgeServiceWorkload.new(name,
                              id,
                              description,
                              package_type,
                              upload_type,
                              repository_type,
                              repository_id,
                              repository,
                              files,
                              revision_type,
                              helm_git_branch,
                              helm_git_tag,
                              helm_yaml_git_tag,
                              helm_repo,
                              yaml_git_branch,
                              terraform_git_branch,
                              terraform_git_tag,
                              created_date,
                              last_modified_dte,
                              created_by,
                              updated_by)
    end

    def to_created_date
      DateTimeHelper.to_rfc3339(created_date)
    end

    def to_last_modified_dte
      DateTimeHelper.to_rfc3339(last_modified_dte)
    end
  end
end
