# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # GetAccountDeviceConsent Model.
  class GetAccountDeviceConsent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of device identifiers
    # @return [Array[Object]]
    attr_accessor :device_list

    # The numeric name of the account, including leading zeros.
    # @return [String]
    attr_accessor :account_name

    # If consent is set at the account level, this value will show the consent
    # level.
    # @return [Integer]
    attr_accessor :all_device_consent

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_list'] = 'deviceList'
      @_hash['account_name'] = 'accountName'
      @_hash['all_device_consent'] = 'allDeviceConsent'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        device_list
        account_name
        all_device_consent
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_list = SKIP, account_name = SKIP,
                   all_device_consent = SKIP)
      @device_list = device_list unless device_list == SKIP
      @account_name = account_name unless account_name == SKIP
      @all_device_consent = all_device_consent unless all_device_consent == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      device_list = hash.key?('deviceList') ? hash['deviceList'] : SKIP
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP
      all_device_consent =
        hash.key?('allDeviceConsent') ? hash['allDeviceConsent'] : SKIP

      # Create object from extracted values.
      GetAccountDeviceConsent.new(device_list,
                                  account_name,
                                  all_device_consent)
    end
  end
end
