# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # HTML error code and description.
  class HttpStatusCodeEnum
    HTTP_STATUS_CODE_ENUM = [
      # TODO: Write general description for ENUM_100_CONTINUE
      ENUM_100_CONTINUE = '100 CONTINUE'.freeze,

      # TODO: Write general description for ENUM_101_SWITCHING_PROTOCOLS
      ENUM_101_SWITCHING_PROTOCOLS = '101 SWITCHING_PROTOCOLS'.freeze,

      # TODO: Write general description for ENUM_102_PROCESSING
      ENUM_102_PROCESSING = '102 PROCESSING'.freeze,

      # TODO: Write general description for ENUM_103_CHECKPOINT
      ENUM_103_CHECKPOINT = '103 CHECKPOINT'.freeze,

      # TODO: Write general description for ENUM_200_OK
      ENUM_200_OK = '200 OK'.freeze,

      # TODO: Write general description for ENUM_201_CREATED
      ENUM_201_CREATED = '201 CREATED'.freeze,

      # TODO: Write general description for ENUM_202_ACCEPTED
      ENUM_202_ACCEPTED = '202 ACCEPTED'.freeze,

      # TODO: Write general description for
      # ENUM_203_NON_AUTHORITATIVE_INFORMATION
      ENUM_203_NON_AUTHORITATIVE_INFORMATION = '203 NON_AUTHORITATIVE_INFORMATION'.freeze,

      # TODO: Write general description for ENUM_204_NO_CONTENT
      ENUM_204_NO_CONTENT = '204 NO_CONTENT'.freeze,

      # TODO: Write general description for ENUM_205_RESET_CONTENT
      ENUM_205_RESET_CONTENT = '205 RESET_CONTENT'.freeze,

      # TODO: Write general description for ENUM_206_PARTIAL_CONTENT
      ENUM_206_PARTIAL_CONTENT = '206 PARTIAL_CONTENT'.freeze,

      # TODO: Write general description for ENUM_207_MULTI_STATUS
      ENUM_207_MULTI_STATUS = '207 MULTI_STATUS'.freeze,

      # TODO: Write general description for ENUM_208_ALREADY_REPORTED
      ENUM_208_ALREADY_REPORTED = '208 ALREADY_REPORTED'.freeze,

      # TODO: Write general description for ENUM_226_IM_USED
      ENUM_226_IM_USED = '226 IM_USED'.freeze,

      # TODO: Write general description for ENUM_300_MULTIPLE_CHOICES
      ENUM_300_MULTIPLE_CHOICES = '300 MULTIPLE_CHOICES'.freeze,

      # TODO: Write general description for ENUM_301_MOVED_PERMANENTLY
      ENUM_301_MOVED_PERMANENTLY = '301 MOVED_PERMANENTLY'.freeze,

      # TODO: Write general description for ENUM_302_FOUND
      ENUM_302_FOUND = '302 FOUND'.freeze,

      # TODO: Write general description for ENUM_302_MOVED_TEMPORARILY
      ENUM_302_MOVED_TEMPORARILY = '302 MOVED_TEMPORARILY'.freeze,

      # TODO: Write general description for ENUM_303_SEE_OTHER
      ENUM_303_SEE_OTHER = '303 SEE_OTHER'.freeze,

      # TODO: Write general description for ENUM_304_NOT_MODIFIED
      ENUM_304_NOT_MODIFIED = '304 NOT_MODIFIED'.freeze,

      # TODO: Write general description for ENUM_305_USE_PROXY
      ENUM_305_USE_PROXY = '305 USE_PROXY'.freeze,

      # TODO: Write general description for ENUM_307_TEMPORARY_REDIRECT
      ENUM_307_TEMPORARY_REDIRECT = '307 TEMPORARY_REDIRECT'.freeze,

      # TODO: Write general description for ENUM_308_PERMANENT_REDIRECT
      ENUM_308_PERMANENT_REDIRECT = '308 PERMANENT_REDIRECT'.freeze,

      # TODO: Write general description for ENUM_400_BAD_REQUEST
      ENUM_400_BAD_REQUEST = '400 BAD_REQUEST'.freeze,

      # TODO: Write general description for ENUM_401_UNAUTHORIZED
      ENUM_401_UNAUTHORIZED = '401 UNAUTHORIZED'.freeze,

      # TODO: Write general description for ENUM_402_PAYMENT_REQUIRED
      ENUM_402_PAYMENT_REQUIRED = '402 PAYMENT_REQUIRED'.freeze,

      # TODO: Write general description for ENUM_403_FORBIDDEN
      ENUM_403_FORBIDDEN = '403 FORBIDDEN'.freeze,

      # TODO: Write general description for ENUM_404_NOT_FOUND
      ENUM_404_NOT_FOUND = '404 NOT_FOUND'.freeze,

      # TODO: Write general description for ENUM_405_METHOD_NOT_ALLOWED
      ENUM_405_METHOD_NOT_ALLOWED = '405 METHOD_NOT_ALLOWED'.freeze,

      # TODO: Write general description for ENUM_406_NOT_ACCEPTABLE
      ENUM_406_NOT_ACCEPTABLE = '406 NOT_ACCEPTABLE'.freeze,

      # TODO: Write general description for
      # ENUM_407_PROXY_AUTHENTICATION_REQUIRED
      ENUM_407_PROXY_AUTHENTICATION_REQUIRED = '407 PROXY_AUTHENTICATION_REQUIRED'.freeze,

      # TODO: Write general description for ENUM_408_REQUEST_TIMEOUT
      ENUM_408_REQUEST_TIMEOUT = '408 REQUEST_TIMEOUT'.freeze,

      # TODO: Write general description for ENUM_409_CONFLICT
      ENUM_409_CONFLICT = '409 CONFLICT'.freeze,

      # TODO: Write general description for ENUM_410_GONE
      ENUM_410_GONE = '410 GONE'.freeze,

      # TODO: Write general description for ENUM_411_LENGTH_REQUIRED
      ENUM_411_LENGTH_REQUIRED = '411 LENGTH_REQUIRED'.freeze,

      # TODO: Write general description for ENUM_412_PRECONDITION_FAILED
      ENUM_412_PRECONDITION_FAILED = '412 PRECONDITION_FAILED'.freeze,

      # TODO: Write general description for ENUM_413_PAYLOAD_TOO_LARGE
      ENUM_413_PAYLOAD_TOO_LARGE = '413 PAYLOAD_TOO_LARGE'.freeze,

      # TODO: Write general description for ENUM_413_REQUEST_ENTITY_TOO_LARGE
      ENUM_413_REQUEST_ENTITY_TOO_LARGE = '413 REQUEST_ENTITY_TOO_LARGE'.freeze,

      # TODO: Write general description for ENUM_414_URI_TOO_LONG
      ENUM_414_URI_TOO_LONG = '414 URI_TOO_LONG'.freeze,

      # TODO: Write general description for ENUM_414_REQUEST_URI_TOO_LONG
      ENUM_414_REQUEST_URI_TOO_LONG = '414 REQUEST_URI_TOO_LONG'.freeze,

      # TODO: Write general description for ENUM_415_UNSUPPORTED_MEDIA_TYPE
      ENUM_415_UNSUPPORTED_MEDIA_TYPE = '415 UNSUPPORTED_MEDIA_TYPE'.freeze,

      # TODO: Write general description for
      # ENUM_416_REQUESTED_RANGE_NOT_SATISFIABLE
      ENUM_416_REQUESTED_RANGE_NOT_SATISFIABLE = '416 REQUESTED_RANGE_NOT_SATISFIABLE'.freeze,

      # TODO: Write general description for ENUM_417_EXPECTATION_FAILED
      ENUM_417_EXPECTATION_FAILED = '417 EXPECTATION_FAILED'.freeze,

      # TODO: Write general description for ENUM_418_I_AM_A_TEAPOT
      ENUM_418_I_AM_A_TEAPOT = '418 I_AM_A_TEAPOT'.freeze,

      # TODO: Write general description for
      # ENUM_419_INSUFFICIENT_SPACE_ON_RESOURCE
      ENUM_419_INSUFFICIENT_SPACE_ON_RESOURCE = '419 INSUFFICIENT_SPACE_ON_RESOURCE'.freeze,

      # TODO: Write general description for ENUM_420_METHOD_FAILURE
      ENUM_420_METHOD_FAILURE = '420 METHOD_FAILURE'.freeze,

      # TODO: Write general description for ENUM_421_DESTINATION_LOCKED
      ENUM_421_DESTINATION_LOCKED = '421 DESTINATION_LOCKED'.freeze,

      # TODO: Write general description for ENUM_422_UNPROCESSABLE_ENTITY
      ENUM_422_UNPROCESSABLE_ENTITY = '422 UNPROCESSABLE_ENTITY'.freeze,

      # TODO: Write general description for ENUM_423_LOCKED
      ENUM_423_LOCKED = '423 LOCKED'.freeze,

      # TODO: Write general description for ENUM_424_FAILED_DEPENDENCY
      ENUM_424_FAILED_DEPENDENCY = '424 FAILED_DEPENDENCY'.freeze,

      # TODO: Write general description for ENUM_425_TOO_EARLY
      ENUM_425_TOO_EARLY = '425 TOO_EARLY'.freeze,

      # TODO: Write general description for ENUM_426_UPGRADE_REQUIRED
      ENUM_426_UPGRADE_REQUIRED = '426 UPGRADE_REQUIRED'.freeze,

      # TODO: Write general description for ENUM_428_PRECONDITION_REQUIRED
      ENUM_428_PRECONDITION_REQUIRED = '428 PRECONDITION_REQUIRED'.freeze,

      # TODO: Write general description for ENUM_429_TOO_MANY_REQUESTS
      ENUM_429_TOO_MANY_REQUESTS = '429 TOO_MANY_REQUESTS'.freeze,

      # TODO: Write general description for
      # ENUM_431_REQUEST_HEADER_FIELDS_TOO_LARGE
      ENUM_431_REQUEST_HEADER_FIELDS_TOO_LARGE = '431 REQUEST_HEADER_FIELDS_TOO_LARGE'.freeze,

      # TODO: Write general description for
      # ENUM_451_UNAVAILABLE_FOR_LEGAL_REASONS
      ENUM_451_UNAVAILABLE_FOR_LEGAL_REASONS = '451 UNAVAILABLE_FOR_LEGAL_REASONS'.freeze,

      # TODO: Write general description for ENUM_500_INTERNAL_SERVER_ERROR
      ENUM_500_INTERNAL_SERVER_ERROR = '500 INTERNAL_SERVER_ERROR'.freeze,

      # TODO: Write general description for ENUM_501_NOT_IMPLEMENTED
      ENUM_501_NOT_IMPLEMENTED = '501 NOT_IMPLEMENTED'.freeze,

      # TODO: Write general description for ENUM_502_BAD_GATEWAY
      ENUM_502_BAD_GATEWAY = '502 BAD_GATEWAY'.freeze,

      # TODO: Write general description for ENUM_503_SERVICE_UNAVAILABLE
      ENUM_503_SERVICE_UNAVAILABLE = '503 SERVICE_UNAVAILABLE'.freeze,

      # TODO: Write general description for ENUM_504_GATEWAY_TIMEOUT
      ENUM_504_GATEWAY_TIMEOUT = '504 GATEWAY_TIMEOUT'.freeze,

      # TODO: Write general description for ENUM_505_HTTP_VERSION_NOT_SUPPORTED
      ENUM_505_HTTP_VERSION_NOT_SUPPORTED = '505 HTTP_VERSION_NOT_SUPPORTED'.freeze,

      # TODO: Write general description for ENUM_506_VARIANT_ALSO_NEGOTIATES
      ENUM_506_VARIANT_ALSO_NEGOTIATES = '506 VARIANT_ALSO_NEGOTIATES'.freeze,

      # TODO: Write general description for ENUM_507_INSUFFICIENT_STORAGE
      ENUM_507_INSUFFICIENT_STORAGE = '507 INSUFFICIENT_STORAGE'.freeze,

      # TODO: Write general description for ENUM_508_LOOP_DETECTED
      ENUM_508_LOOP_DETECTED = '508 LOOP_DETECTED'.freeze,

      # TODO: Write general description for ENUM_509_BANDWIDTH_LIMIT_EXCEEDED
      ENUM_509_BANDWIDTH_LIMIT_EXCEEDED = '509 BANDWIDTH_LIMIT_EXCEEDED'.freeze,

      # TODO: Write general description for ENUM_510_NOT_EXTENDED
      ENUM_510_NOT_EXTENDED = '510 NOT_EXTENDED'.freeze,

      # TODO: Write general description for
      # ENUM_511_NETWORK_AUTHENTICATION_REQUIRED
      ENUM_511_NETWORK_AUTHENTICATION_REQUIRED = '511 NETWORK_AUTHENTICATION_REQUIRED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      HTTP_STATUS_CODE_ENUM.include?(value)
    end
  end
end
