# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # IP pool that is available to the account.
  class IPPool < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of the IP pool.
    # @return [String]
    attr_accessor :pool_name

    # The type of IP pool, such as “Static IP” or “Dynamic IP.”
    # @return [String]
    attr_accessor :pool_type

    # True if this is the default IP pool for the account.
    # @return [TrueClass | FalseClass]
    attr_accessor :is_default_pool

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pool_name'] = 'poolName'
      @_hash['pool_type'] = 'poolType'
      @_hash['is_default_pool'] = 'isDefaultPool'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pool_name
        pool_type
        is_default_pool
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pool_name = SKIP,
                   pool_type = SKIP,
                   is_default_pool = SKIP)
      @pool_name = pool_name unless pool_name == SKIP
      @pool_type = pool_type unless pool_type == SKIP
      @is_default_pool = is_default_pool unless is_default_pool == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pool_name = hash.key?('poolName') ? hash['poolName'] : SKIP
      pool_type = hash.key?('poolType') ? hash['poolType'] : SKIP
      is_default_pool =
        hash.key?('isDefaultPool') ? hash['isDefaultPool'] : SKIP

      # Create object from extracted values.
      IPPool.new(pool_name,
                 pool_type,
                 is_default_pool)
    end
  end
end
