# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # M5gBiaddressAndcustomerinfo Model.
  class M5gBiaddressAndcustomerinfo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [M5gBiprimaryPlaceofuse]
    attr_accessor :primary_placeofuse

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['primary_placeofuse'] = 'primaryPlaceofuse'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        primary_placeofuse
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(primary_placeofuse = SKIP)
      @primary_placeofuse = primary_placeofuse unless primary_placeofuse == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      primary_placeofuse = M5gBiprimaryPlaceofuse.from_hash(hash['primaryPlaceofuse']) if
        hash['primaryPlaceofuse']

      # Create object from extracted values.
      M5gBiaddressAndcustomerinfo.new(primary_placeofuse)
    end
  end
end
