# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ManagedAccountsProvisionRequest Model.
  class ManagedAccountsProvisionRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Managed account identifier
    # @return [String]
    attr_accessor :account_name

    # Primary Account identifier
    # @return [String]
    attr_accessor :paccount_name

    # Service name
    # @return [ServiceNameEnum]
    attr_accessor :service_name

    # SKU name
    # @return [String]
    attr_accessor :type

    # Transaction identifier returned by add request
    # @return [String]
    attr_accessor :txid

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['paccount_name'] = 'paccountName'
      @_hash['service_name'] = 'serviceName'
      @_hash['type'] = 'type'
      @_hash['txid'] = 'txid'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = nil,
                   paccount_name = nil,
                   service_name = ServiceNameEnum::LOCATION,
                   type = nil,
                   txid = nil)
      @account_name = account_name
      @paccount_name = paccount_name
      @service_name = service_name
      @type = type
      @txid = txid
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : nil
      paccount_name = hash.key?('paccountName') ? hash['paccountName'] : nil
      service_name = hash['serviceName'] ||= ServiceNameEnum::LOCATION
      type = hash.key?('type') ? hash['type'] : nil
      txid = hash.key?('txid') ? hash['txid'] : nil

      # Create object from extracted values.
      ManagedAccountsProvisionRequest.new(account_name,
                                          paccount_name,
                                          service_name,
                                          type,
                                          txid)
    end
  end
end
