# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ManagedAccountsGetAllResponse Model.
  class ManagedAccountsGetAllResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account Name
    # @return [String]
    attr_accessor :account_name

    # Account Name
    # @return [Array[ManagedAccAddedList]]
    attr_accessor :managed_acc_added_list

    # Account Name
    # @return [Array[ManagedAccProvisionedList]]
    attr_accessor :managed_acc_provisioned_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['managed_acc_added_list'] = 'ManagedAccAddedList'
      @_hash['managed_acc_provisioned_list'] = 'managedAccProvisionedList'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_name
        managed_acc_added_list
        managed_acc_provisioned_list
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = SKIP,
                   managed_acc_added_list = SKIP,
                   managed_acc_provisioned_list = SKIP)
      @account_name = account_name unless account_name == SKIP
      @managed_acc_added_list = managed_acc_added_list unless managed_acc_added_list == SKIP
      unless managed_acc_provisioned_list == SKIP
        @managed_acc_provisioned_list =
          managed_acc_provisioned_list
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP
      # Parameter is an array, so we need to iterate through it
      managed_acc_added_list = nil
      unless hash['ManagedAccAddedList'].nil?
        managed_acc_added_list = []
        hash['ManagedAccAddedList'].each do |structure|
          managed_acc_added_list << (ManagedAccAddedList.from_hash(structure) if structure)
        end
      end

      managed_acc_added_list = SKIP unless hash.key?('ManagedAccAddedList')
      # Parameter is an array, so we need to iterate through it
      managed_acc_provisioned_list = nil
      unless hash['managedAccProvisionedList'].nil?
        managed_acc_provisioned_list = []
        hash['managedAccProvisionedList'].each do |structure|
          managed_acc_provisioned_list << (ManagedAccProvisionedList.from_hash(structure) if structure)
        end
      end

      managed_acc_provisioned_list = SKIP unless hash.key?('managedAccProvisionedList')

      # Create object from extracted values.
      ManagedAccountsGetAllResponse.new(account_name,
                                        managed_acc_added_list,
                                        managed_acc_provisioned_list)
    end
  end
end
