# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ManagedAccountsProvisionResponse Model.
  class ManagedAccountsProvisionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Transaction identifier
    # @return [String]
    attr_accessor :txid

    # Account identifier
    # @return [String]
    attr_accessor :account_name

    # Primary Account identifier
    # @return [String]
    attr_accessor :paccount_name

    # Service name
    # @return [ServiceNameEnum]
    attr_accessor :service_name

    # Provision status. Success or Fail
    # @return [String]
    attr_accessor :status

    # Detailed reason
    # @return [String]
    attr_accessor :reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['txid'] = 'txid'
      @_hash['account_name'] = 'accountName'
      @_hash['paccount_name'] = 'paccountName'
      @_hash['service_name'] = 'serviceName'
      @_hash['status'] = 'status'
      @_hash['reason'] = 'reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        txid
        account_name
        paccount_name
        service_name
        status
        reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(txid = SKIP,
                   account_name = SKIP,
                   paccount_name = SKIP,
                   service_name = ServiceNameEnum::LOCATION,
                   status = SKIP,
                   reason = SKIP)
      @txid = txid unless txid == SKIP
      @account_name = account_name unless account_name == SKIP
      @paccount_name = paccount_name unless paccount_name == SKIP
      @service_name = service_name unless service_name == SKIP
      @status = status unless status == SKIP
      @reason = reason unless reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      txid = hash.key?('txid') ? hash['txid'] : SKIP
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP
      paccount_name = hash.key?('paccountName') ? hash['paccountName'] : SKIP
      service_name = hash['serviceName'] ||= ServiceNameEnum::LOCATION
      status = hash.key?('status') ? hash['status'] : SKIP
      reason = hash.key?('reason') ? hash['reason'] : SKIP

      # Create object from extracted values.
      ManagedAccountsProvisionResponse.new(txid,
                                           account_name,
                                           paccount_name,
                                           service_name,
                                           status,
                                           reason)
    end
  end
end
