# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # NetworkNatMode.
  class NetworkNatModeEnum
    NETWORK_NAT_MODE_ENUM = [
      # TODO: Write general description for HIGHAVAILABLE
      HIGHAVAILABLE = 'highAvailable'.freeze,

      # TODO: Write general description for SINGLE
      SINGLE = 'single'.freeze,

      # TODO: Write general description for DISABLE
      DISABLE = 'disable'.freeze
    ].freeze
  end
end
