# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Unit of time.
  class NumericalDataUnitEnum
    NUMERICAL_DATA_UNIT_ENUM = [
      # TODO: Write general description for SECOND
      SECOND = 'SECOND'.freeze,

      # TODO: Write general description for MINUTE
      MINUTE = 'MINUTE'.freeze,

      # TODO: Write general description for HOUR
      HOUR = 'HOUR'.freeze,

      # TODO: Write general description for DAY
      DAY = 'DAY'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NUMERICAL_DATA_UNIT_ENUM.include?(value)
    end
  end
end
