# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Describes value and unit of time.
  class NumericalData < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Numerical value.
    # @return [Integer]
    attr_accessor :value

    # Unit of time.
    # @return [NumericalDataUnitEnum]
    attr_accessor :unit

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['value'] = 'value'
      @_hash['unit'] = 'unit'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        value
        unit
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(value = SKIP,
                   unit = SKIP)
      @value = value unless value == SKIP
      @unit = unit unless unit == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      value = hash.key?('value') ? hash['value'] : SKIP
      unit = hash.key?('unit') ? hash['unit'] : SKIP

      # Create object from extracted values.
      NumericalData.new(value,
                        unit)
    end
  end
end
