# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # The last status of the device's profile as a filter.
  class ProfileStatusFilterEnum
    PROFILE_STATUS_FILTER_ENUM = [
      # TODO: Write general description for ENABLE
      ENABLE = 'ENABLE'.freeze,

      # TODO: Write general description for DISABLE
      DISABLE = 'DISABLE'.freeze,

      # TODO: Write general description for DOWNLOAD_DISABLE
      DOWNLOAD_DISABLE = 'DOWNLOAD_DISABLE'.freeze,

      # TODO: Write general description for DOWNLOAD_ENABLE
      DOWNLOAD_ENABLE = 'DOWNLOAD_ENABLE'.freeze,

      # TODO: Write general description for NOT_DOWNLOADED
      NOT_DOWNLOADED = 'NOT_DOWNLOADED'.freeze,

      # TODO: Write general description for UNKNOWN
      UNKNOWN = 'UNKNOWN'.freeze,

      # TODO: Write general description for DELETE
      DELETE = 'DELETE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PROFILE_STATUS_FILTER_ENUM.include?(value)
    end
  end
end
