# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ProfileRequest2 Model.
  class ProfileRequest2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[DeviceList2]]
    attr_accessor :devices

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :carrier_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :reason_code

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :etf_waiver

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :check_fallback_profile

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['devices'] = 'devices'
      @_hash['account_name'] = 'accountName'
      @_hash['carrier_name'] = 'carrierName'
      @_hash['reason_code'] = 'reasonCode'
      @_hash['etf_waiver'] = 'etfWaiver'
      @_hash['check_fallback_profile'] = 'checkFallbackProfile'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        devices
        account_name
        carrier_name
        reason_code
        etf_waiver
        check_fallback_profile
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(devices = SKIP,
                   account_name = SKIP,
                   carrier_name = SKIP,
                   reason_code = SKIP,
                   etf_waiver = true,
                   check_fallback_profile = false)
      @devices = devices unless devices == SKIP
      @account_name = account_name unless account_name == SKIP
      @carrier_name = carrier_name unless carrier_name == SKIP
      @reason_code = reason_code unless reason_code == SKIP
      @etf_waiver = etf_waiver unless etf_waiver == SKIP
      @check_fallback_profile = check_fallback_profile unless check_fallback_profile == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      devices = nil
      unless hash['devices'].nil?
        devices = []
        hash['devices'].each do |structure|
          devices << (DeviceList2.from_hash(structure) if structure)
        end
      end

      devices = SKIP unless hash.key?('devices')
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP
      carrier_name = hash.key?('carrierName') ? hash['carrierName'] : SKIP
      reason_code = hash.key?('reasonCode') ? hash['reasonCode'] : SKIP
      etf_waiver = hash['etfWaiver'] ||= true
      check_fallback_profile = hash['checkFallbackProfile'] ||= false

      # Create object from extracted values.
      ProfileRequest2.new(devices,
                          account_name,
                          carrier_name,
                          reason_code,
                          etf_waiver,
                          check_fallback_profile)
    end
  end
end
