# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # RepositoryResType.
  class RepositoryResTypeEnum
    REPOSITORY_RES_TYPE_ENUM = [
      # TODO: Write general description for GIT
      GIT = 'Git'.freeze,

      # TODO: Write general description for HELM
      HELM = 'Helm'.freeze,

      # TODO: Write general description for USERUPLOAD
      USERUPLOAD = 'userUpload'.freeze
    ].freeze
  end
end
