# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Possible response codes.
  class ResponseCodeEnum
    RESPONSE_CODE_ENUM = [
      # TODO: Write general description for INVALID_ACCESS
      INVALID_ACCESS = 'INVALID_ACCESS'.freeze,

      # TODO: Write general description for INVALID_PARAMETER
      INVALID_PARAMETER = 'INVALID_PARAMETER'.freeze,

      # TODO: Write general description for INTERNAL_ERROR
      INTERNAL_ERROR = 'INTERNAL_ERROR'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'SUCCESS'.freeze
    ].freeze
  end
end
