# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # RetrievesAvailableFilesResponseList Model.
  class RetrievesAvailableFilesResponseList < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[RetrievesAvailableFilesResponse]]
    attr_accessor :available_files_response

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['available_files_response'] = 'AvailableFilesResponse'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        available_files_response
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(available_files_response = SKIP)
      @available_files_response = available_files_response unless available_files_response == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      available_files_response = nil
      unless hash['AvailableFilesResponse'].nil?
        available_files_response = []
        hash['AvailableFilesResponse'].each do |structure|
          available_files_response << (RetrievesAvailableFilesResponse.from_hash(structure) if structure)
        end
      end

      available_files_response = SKIP unless hash.key?('AvailableFilesResponse')

      # Create object from extracted values.
      RetrievesAvailableFilesResponseList.new(available_files_response)
    end
  end
end
