# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Revision Model.
  class Revision < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :version

    # TODO: Write general description for this method
    # @return [Array[EdgeServiceLaunchParams]]
    attr_accessor :additional_params

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['version'] = 'version'
      @_hash['additional_params'] = 'additionalParams'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        additional_params
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        additional_params
      ]
    end

    def initialize(version = nil,
                   additional_params = SKIP)
      @version = version
      @additional_params = additional_params unless additional_params == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      version = hash.key?('version') ? hash['version'] : nil
      # Parameter is an array, so we need to iterate through it
      additional_params = nil
      unless hash['additionalParams'].nil?
        additional_params = []
        hash['additionalParams'].each do |structure|
          additional_params << (EdgeServiceLaunchParams.from_hash(structure) if structure)
        end
      end

      additional_params = SKIP unless hash.key?('additionalParams')

      # Create object from extracted values.
      Revision.new(version,
                   additional_params)
    end
  end
end
