# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Request for a subscription.
  class SecuritySubscriptionRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of a billing account.
    # @return [String]
    attr_accessor :account_name

    # The Stock Keeping Unit (SKU). Valid skuNumbers for SIM-Secure for IoT
    # are:SIMSec-IoT-Lt”. (Lifetime) Once a license is assigned to a SIM, the
    # SIM-Secure feature is enabled for the life of the
    # SIM.“TS-BUNDLE-KTO-SIMSEC-MRC”. (Bundle) The SIM-Secure Flex license can
    # be assigned to or removed from a SIM at any time. This SKU is bundled with
    # other ThingSpace Services.*“SIMSec-IoT”. (Flex) The SIM-Secure Flex
    # license can be assigned to or removed from a SIM at any time. This SKU is
    # purchased a la carte.
    # @return [String]
    attr_accessor :sku_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_name'] = 'accountName'
      @_hash['sku_number'] = 'skuNumber'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_name
        sku_number
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_name = SKIP,
                   sku_number = SKIP)
      @account_name = account_name unless account_name == SKIP
      @sku_number = sku_number unless sku_number == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_name = hash.key?('accountName') ? hash['accountName'] : SKIP
      sku_number = hash.key?('skuNumber') ? hash['skuNumber'] : SKIP

      # Create object from extracted values.
      SecuritySubscriptionRequest.new(account_name,
                                      sku_number)
    end
  end
end
