# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Service which is selected.
  class SelectedService < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Name of the service needs to be deployed.
    # @return [String]
    attr_accessor :name

    # Name of the service user is created.
    # @return [String]
    attr_accessor :version

    # Can have any value as - DRAFT, DESIGN, TESTING, PUBLISH, CERTIFY,
    # READY_TO_USE, DEPRECATE, DELETED.
    # @return [ServiceStateEnum]
    attr_accessor :state

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['version'] = 'version'
      @_hash['state'] = 'state'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        version
        state
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name = SKIP,
                   version = SKIP,
                   state = SKIP)
      @name = name unless name == SKIP
      @version = version unless version == SKIP
      @state = state unless state == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      version = hash.key?('version') ? hash['version'] : SKIP
      state = hash.key?('state') ? hash['state'] : SKIP

      # Create object from extracted values.
      SelectedService.new(name,
                          version,
                          state)
    end
  end
end
