# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Service name
  class ServiceNameEnum
    SERVICE_NAME_ENUM = [
      # TODO: Write general description for LOCATION
      LOCATION = 'Location'.freeze,

      # TODO: Write general description for FOTA
      FOTA = 'fota'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      SERVICE_NAME_ENUM.include?(value)
    end
  end
end
