# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Key service plan trigger attribute.
  class ServicePlanTriggerAttribute < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ServicePlan name will be listed here.
    # @return [String]
    attr_accessor :key

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['key'] = 'key'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        key
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(key = SKIP)
      @key = key unless key == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      key = hash.key?('key') ? hash['key'] : SKIP

      # Create object from extracted values.
      ServicePlanTriggerAttribute.new(key)
    end
  end
end
