# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # ServiceLaunchTerraformGitTag Model.
  class ServiceLaunchTerraformGitTag < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :tag_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :terraform_path

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tag_name'] = 'tagName'
      @_hash['terraform_path'] = 'terraformPath'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        tag_name
        terraform_path
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(tag_name = SKIP,
                   terraform_path = SKIP)
      @tag_name = tag_name unless tag_name == SKIP
      @terraform_path = terraform_path unless terraform_path == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      tag_name = hash.key?('tagName') ? hash['tagName'] : SKIP
      terraform_path = hash.key?('terraformPath') ? hash['terraformPath'] : SKIP

      # Create object from extracted values.
      ServiceLaunchTerraformGitTag.new(tag_name,
                                       terraform_path)
    end
  end
end
