# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # SMS messages sent by all M2M devices associated with a billing account.
  class SMSMessage < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # One or more IDs of the device that sent the message.
    # @return [Array[DeviceId]]
    attr_accessor :device_ids

    # The contents of the SMS message.
    # @return [String]
    attr_accessor :message

    # The date and time that the message was received by the Verizon ThingSpace
    # Platform.
    # @return [String]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_ids'] = 'deviceIds'
      @_hash['message'] = 'message'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        device_ids
        message
        timestamp
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_ids = SKIP,
                   message = SKIP,
                   timestamp = SKIP)
      @device_ids = device_ids unless device_ids == SKIP
      @message = message unless message == SKIP
      @timestamp = timestamp unless timestamp == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      device_ids = nil
      unless hash['deviceIds'].nil?
        device_ids = []
        hash['deviceIds'].each do |structure|
          device_ids << (DeviceId.from_hash(structure) if structure)
        end
      end

      device_ids = SKIP unless hash.key?('deviceIds')
      message = hash.key?('message') ? hash['message'] : SKIP
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : SKIP

      # Create object from extracted values.
      SMSMessage.new(device_ids,
                     message,
                     timestamp)
    end
  end
end
