# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Sorts the list in ascending/descending order.
  class SortDirectionEnum
    SORT_DIRECTION_ENUM = [
      # TODO: Write general description for ASC
      ASC = 'ASC'.freeze,

      # TODO: Write general description for DESC
      DESC = 'DESC'.freeze
    ].freeze
  end
end
