# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # StatusList Model.
  class StatusList < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account name
    # @return [String]
    attr_accessor :id

    # Success or Fail
    # @return [String]
    attr_accessor :status

    # detailed reason
    # @return [String]
    attr_accessor :reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['status'] = 'status'
      @_hash['reason'] = 'reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        status
        reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = SKIP,
                   status = SKIP,
                   reason = SKIP)
      @id = id unless id == SKIP
      @status = status unless status == SKIP
      @reason = reason unless reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      reason = hash.key?('reason') ? hash['reason'] : SKIP

      # Create object from extracted values.
      StatusList.new(id,
                     status,
                     reason)
    end
  end
end
