# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Default type for ueIdentityType.
  class UEIdentityTypeEnum
    UE_IDENTITY_TYPE_ENUM = [
      # TODO: Write general description for IPADDRESS
      IPADDRESS = 'IPAddress'.freeze,

      # TODO: Write general description for MSISDN
      MSISDN = 'MSISDN'.freeze,

      # TODO: Write general description for IMEI
      IMEI = 'IMEI'.freeze,

      # TODO: Write general description for MDN
      MDN = 'MDN'.freeze,

      # TODO: Write general description for GPSI
      GPSI = 'GPSI'.freeze
    ].freeze
  end
end
