# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Allowed values are: GIT files (PULL_FROM_REPO), MANUAL_UPLOAD.
  class UploadTypeEnum
    UPLOAD_TYPE_ENUM = [
      # TODO: Write general description for PULL_FROM_REPO
      PULL_FROM_REPO = 'PULL_FROM_REPO'.freeze,

      # TODO: Write general description for MANUAL_UPLOAD
      MANUAL_UPLOAD = 'MANUAL_UPLOAD'.freeze
    ].freeze
  end
end
