# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # user_role.
  class UserRoleEnum
    USER_ROLE_ENUM = [
      # TODO: Write general description for ADMIN
      ADMIN = 'ADMIN'.freeze,

      # TODO: Write general description for USER
      USER = 'USER'.freeze,

      # TODO: Write general description for ORGADMIN
      ORGADMIN = 'ORGADMIN'.freeze
    ].freeze
  end
end
