# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # A JSON object for each device that was included in the request, showing the
  # device IMEI, the status of the addition or removal, and additional
  # information about the status.
  class V1DeviceListItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Device IMEI.
    # @return [String]
    attr_accessor :device_id

    # Whether the device was successfully added or removed from the campaign.
    # @return [String]
    attr_accessor :status

    # Additional details about the status.
    # @return [String]
    attr_accessor :reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_id'] = 'deviceId'
      @_hash['status'] = 'status'
      @_hash['reason'] = 'Reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        device_id
        status
        reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_id = SKIP,
                   status = SKIP,
                   reason = SKIP)
      @device_id = device_id unless device_id == SKIP
      @status = status unless status == SKIP
      @reason = reason unless reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      device_id = hash.key?('deviceId') ? hash['deviceId'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      reason = hash.key?('Reason') ? hash['Reason'] : SKIP

      # Create object from extracted values.
      V1DeviceListItem.new(device_id,
                           status,
                           reason)
    end
  end
end
