# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Device with id in IMEI.
  class V2DeviceStatus < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Device IMEI.
    # @return [String]
    attr_accessor :device_id

    # Success or failure.
    # @return [String]
    attr_accessor :status

    # Result reason.
    # @return [String]
    attr_accessor :result_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_id'] = 'deviceId'
      @_hash['status'] = 'status'
      @_hash['result_reason'] = 'resultReason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        result_reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_id = nil,
                   status = nil,
                   result_reason = SKIP)
      @device_id = device_id
      @status = status
      @result_reason = result_reason unless result_reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      device_id = hash.key?('deviceId') ? hash['deviceId'] : nil
      status = hash.key?('status') ? hash['status'] : nil
      result_reason = hash.key?('resultReason') ? hash['resultReason'] : SKIP

      # Create object from extracted values.
      V2DeviceStatus.new(device_id,
                         status,
                         result_reason)
    end
  end
end
