# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Campaign history.
  class V3CampaignDevice < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Total device count.
    # @return [Integer]
    attr_accessor :total_device

    # Has more report flag.
    # @return [TrueClass | FalseClass]
    attr_accessor :has_more_data

    # Device identifier.
    # @return [String]
    attr_accessor :last_seen_device_id

    # Maximum page size.
    # @return [Integer]
    attr_accessor :max_page_size

    # List of devices with id in IMEI.
    # @return [Array[V3DeviceStatus]]
    attr_accessor :device_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['total_device'] = 'totalDevice'
      @_hash['has_more_data'] = 'hasMoreData'
      @_hash['last_seen_device_id'] = 'lastSeenDeviceId'
      @_hash['max_page_size'] = 'maxPageSize'
      @_hash['device_list'] = 'deviceList'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        total_device
        last_seen_device_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(has_more_data = nil,
                   max_page_size = nil,
                   device_list = nil,
                   total_device = SKIP,
                   last_seen_device_id = SKIP)
      @total_device = total_device unless total_device == SKIP
      @has_more_data = has_more_data
      @last_seen_device_id = last_seen_device_id unless last_seen_device_id == SKIP
      @max_page_size = max_page_size
      @device_list = device_list
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      has_more_data = hash.key?('hasMoreData') ? hash['hasMoreData'] : nil
      max_page_size = hash.key?('maxPageSize') ? hash['maxPageSize'] : nil
      # Parameter is an array, so we need to iterate through it
      device_list = nil
      unless hash['deviceList'].nil?
        device_list = []
        hash['deviceList'].each do |structure|
          device_list << (V3DeviceStatus.from_hash(structure) if structure)
        end
      end

      device_list = nil unless hash.key?('deviceList')
      total_device = hash.key?('totalDevice') ? hash['totalDevice'] : SKIP
      last_seen_device_id =
        hash.key?('lastSeenDeviceId') ? hash['lastSeenDeviceId'] : SKIP

      # Create object from extracted values.
      V3CampaignDevice.new(has_more_data,
                           max_page_size,
                           device_list,
                           total_device,
                           last_seen_device_id)
    end
  end
end
