# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Campaign dates and time windows.
  class V3ChangeCampaignDatesRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Campaign start date.
    # @return [Date]
    attr_accessor :start_date

    # Campaign end date.
    # @return [Date]
    attr_accessor :end_date

    # List of allowed campaign time windows.
    # @return [Array[V3TimeWindow]]
    attr_accessor :campaign_time_window_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['start_date'] = 'startDate'
      @_hash['end_date'] = 'endDate'
      @_hash['campaign_time_window_list'] = 'campaignTimeWindowList'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        campaign_time_window_list
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(start_date = nil,
                   end_date = nil,
                   campaign_time_window_list = SKIP)
      @start_date = start_date
      @end_date = end_date
      unless campaign_time_window_list == SKIP
        @campaign_time_window_list =
          campaign_time_window_list
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      start_date = hash.key?('startDate') ? hash['startDate'] : nil
      end_date = hash.key?('endDate') ? hash['endDate'] : nil
      # Parameter is an array, so we need to iterate through it
      campaign_time_window_list = nil
      unless hash['campaignTimeWindowList'].nil?
        campaign_time_window_list = []
        hash['campaignTimeWindowList'].each do |structure|
          campaign_time_window_list << (V3TimeWindow.from_hash(structure) if structure)
        end
      end

      campaign_time_window_list = SKIP unless hash.key?('campaignTimeWindowList')

      # Create object from extracted values.
      V3ChangeCampaignDatesRequest.new(start_date,
                                       end_date,
                                       campaign_time_window_list)
    end
  end
end
