# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # Service type e.g. Installation, Operations, Custom.
  class WorkflowTypeEnum
    WORKFLOW_TYPE_ENUM = [
      # TODO: Write general description for INSTALLATION
      INSTALLATION = 'INSTALLATION'.freeze,

      # TODO: Write general description for OPERATIONS
      OPERATIONS = 'OPERATIONS'.freeze,

      # TODO: Write general description for CUSTOM
      CUSTOM = 'CUSTOM'.freeze
    ].freeze
  end
end
