# verizon
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Verizon
  # An enum for SDK environments.
  class Environment
    ENVIRONMENT = [
      PRODUCTION = 'Production'.freeze,
      MOCK_SERVER_FOR_LIMITED_AVAILABILITY_SEE_QUICK_START = 'Mock server for limited availability, see quick start'.freeze
    ].freeze
  end

  # An enum for API servers.
  class Server
    SERVER = [
      EDGE_DISCOVERY = 'Edge Discovery'.freeze,
      THINGSPACE = 'Thingspace'.freeze,
      OAUTH_SERVER = 'OAuth Server'.freeze,
      M2M = 'M2M'.freeze,
      DEVICE_LOCATION = 'Device Location'.freeze,
      SUBSCRIPTION_SERVER = 'Subscription Server'.freeze,
      SOFTWARE_MANAGEMENT_V1 = 'Software Management V1'.freeze,
      SOFTWARE_MANAGEMENT_V2 = 'Software Management V2'.freeze,
      SOFTWARE_MANAGEMENT_V3 = 'Software Management V3'.freeze,
      PERFORMANCE = 'Performance'.freeze,
      DEVICE_DIAGNOSTICS = 'Device Diagnostics'.freeze,
      CLOUD_CONNECTOR = 'Cloud Connector'.freeze,
      HYPER_PRECISE_LOCATION = 'Hyper Precise Location'.freeze,
      SERVICES = 'Services'.freeze,
      QUALITY_OF_SERVICE = 'Quality Of Service'.freeze
    ].freeze
  end

  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration < CoreLibrary::HttpClientConfiguration
    # The attribute readers for properties.
    attr_reader :environment, :thingspace_oauth_credentials,
                :vz_m2m_token_credentials

    class << self
      attr_reader :environments
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 60,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put], http_callback: nil,
      environment: Environment::PRODUCTION, thingspace_oauth_credentials: nil,
      vz_m2m_token_credentials: nil
    )

      super connection: connection, adapter: adapter, timeout: timeout,
            max_retries: max_retries, retry_interval: retry_interval,
            backoff_factor: backoff_factor, retry_statuses: retry_statuses,
            retry_methods: retry_methods, http_callback: http_callback

      # Current API environment
      @environment = String(environment)

      # The object holding OAuth 2 Client Credentials Grant credentials
      @thingspace_oauth_credentials = thingspace_oauth_credentials

      # The object holding Custom Header Signature credentials
      @vz_m2m_token_credentials = vz_m2m_token_credentials

      # The Http Client to use for making requests.
      set_http_client CoreLibrary::FaradayClient.new(self)
    end

    def clone_with(connection: nil, adapter: nil, timeout: nil,
                   max_retries: nil, retry_interval: nil, backoff_factor: nil,
                   retry_statuses: nil, retry_methods: nil, http_callback: nil,
                   environment: nil, thingspace_oauth_credentials: nil,
                   vz_m2m_token_credentials: nil)
      connection ||= self.connection
      adapter ||= self.adapter
      timeout ||= self.timeout
      max_retries ||= self.max_retries
      retry_interval ||= self.retry_interval
      backoff_factor ||= self.backoff_factor
      retry_statuses ||= self.retry_statuses
      retry_methods ||= self.retry_methods
      http_callback ||= self.http_callback
      environment ||= self.environment
      thingspace_oauth_credentials ||= self.thingspace_oauth_credentials
      vz_m2m_token_credentials ||= self.vz_m2m_token_credentials

      Configuration.new(
        connection: connection, adapter: adapter, timeout: timeout,
        max_retries: max_retries, retry_interval: retry_interval,
        backoff_factor: backoff_factor, retry_statuses: retry_statuses,
        retry_methods: retry_methods, http_callback: http_callback,
        environment: environment,
        thingspace_oauth_credentials: thingspace_oauth_credentials,
        vz_m2m_token_credentials: vz_m2m_token_credentials
      )
    end


    # All the environments the SDK can run in.
    ENVIRONMENTS = {
      Environment::PRODUCTION => {
        Server::EDGE_DISCOVERY => 'https://5gedge.verizon.com/api/mec/eds',
        Server::THINGSPACE => 'https://thingspace.verizon.com/api',
        Server::OAUTH_SERVER => 'https://thingspace.verizon.com/api/ts/v1',
        Server::M2M => 'https://thingspace.verizon.com/api/m2m',
        Server::DEVICE_LOCATION => 'https://thingspace.verizon.com/api/loc/v1',
        Server::SUBSCRIPTION_SERVER => 'https://thingspace.verizon.com/api/subsc/v1',
        Server::SOFTWARE_MANAGEMENT_V1 => 'https://thingspace.verizon.com/api/fota/v1',
        Server::SOFTWARE_MANAGEMENT_V2 => 'https://thingspace.verizon.com/api/fota/v2',
        Server::SOFTWARE_MANAGEMENT_V3 => 'https://thingspace.verizon.com/api/fota/v3',
        Server::PERFORMANCE => 'https://5gedge.verizon.com/api/mec',
        Server::DEVICE_DIAGNOSTICS => 'https://thingspace.verizon.com/api/diagnostics/v1',
        Server::CLOUD_CONNECTOR => 'https://thingspace.verizon.com/api/cc/v1',
        Server::HYPER_PRECISE_LOCATION => 'https://thingspace.verizon.com/api/hyper-precise/v1',
        Server::SERVICES => 'https://5gedge.verizon.com/api/mec/services',
        Server::QUALITY_OF_SERVICE => 'https://thingspace.verizon.com/api/m2m/v1/devices'
      },
      Environment::MOCK_SERVER_FOR_LIMITED_AVAILABILITY_SEE_QUICK_START => {
        Server::EDGE_DISCOVERY => 'https://mock.thingspace.verizon.com/api/mec/eds',
        Server::THINGSPACE => 'https://mock.thingspace.verizon.com/api',
        Server::OAUTH_SERVER => 'https://mock.thingspace.verizon.com/api/ts/v1',
        Server::M2M => 'https://mock.thingspace.verizon.com/api/m2m',
        Server::DEVICE_LOCATION => 'https://mock.thingspace.verizon.com/api/loc/v1',
        Server::SUBSCRIPTION_SERVER => 'https://mock.thingspace.verizon.com/api/subsc/v1',
        Server::SOFTWARE_MANAGEMENT_V1 => 'https://mock.thingspace.verizon.com/api/fota/v1',
        Server::SOFTWARE_MANAGEMENT_V2 => 'https://mock.thingspace.verizon.com/api/fota/v2',
        Server::SOFTWARE_MANAGEMENT_V3 => 'https://mock.thingspace.verizon.com/api/fota/v3',
        Server::PERFORMANCE => 'https://mock.thingspace.verizon.com/api/mec',
        Server::DEVICE_DIAGNOSTICS => 'https://mock.thingspace.verizon.com/api/diagnostics/v1',
        Server::CLOUD_CONNECTOR => 'https://mock.thingspace.verizon.com/api/cc/v1',
        Server::HYPER_PRECISE_LOCATION => 'https://mock.thingspace.verizon.com/api/hyper-precise/v1',
        Server::SERVICES => 'https://mock.thingspace.verizon.com/api/mec/services',
        Server::QUALITY_OF_SERVICE => 'https://mock.thingspace.verizon.com/api/m2m/v1/devices'
      }
    }.freeze

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] server The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def get_base_uri(server = Server::EDGE_DISCOVERY)
      ENVIRONMENTS[environment][server].clone
    end
  end
end
